# ParticleX Configuration
# https://github.com/theme-particlex/hexo-theme-particlex
# 图标网址 https://fontawesome.com/icons/eye?f=classic&s=solid

# 头像图片
avatar: /images/avatar.jpg

# 主页的背景图片，动图也行
background:
#    - /images/background/01.png
    - /images/background/02.jpeg
#    - /images/background/03.png
#    - /images/background/04.png

# 加载动画图片
loading: /images/loading.gif

# Optional colors for category and tag
colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"
    - "#ffb3d5"
    - "#14bdd5"
    - "#17b0f5"
    - "#11b6a7"
    - "#ff8e84"
    - "#ffc4e6"
    - "#28cfe6"
    - "#2ab1f6"
    - "#22c7b8"
    - "#ff9fa5"
    - "#ffd5f7"
    - "#3cd0e7"
    - "#3db2f7"
    - "#33d8c9"
    - "#ffa0b6"
    - "#ffe6f8"
    - "#4dd1e8"
    - "#4eb3f8"
    - "#44e9da"
    - "#ffb1c7"
    - "#fff7f9"
    - "#5ed2e9"
    - "#5fb4f9"
    - "#55fabf"
    - "#ffc2d8"
    - "#e6faff"
    - "#6ed3ea"
    - "#6fb5fa"
    - "#66fbc0"
    - "#ffd3e9"
    - "#d5f9ff"
    - "#7ed4eb"
    - "#7fb6fb"
    - "#77fcc1"
    - "#ffe4fa"
    - "#c4f8ff"
    - "#8ed5ec"
    - "#8fb7fc"
    - "#88fdd2"
    - "#fff5fb"
    - "#b3f7ff"
    - "#9ed6ed"
    - "#9fb8fd"
    - "#99fee3"
    - "#e6e6ff"
    - "#a2f6ff"
    - "#aed7ee"
    - "#afb9fe"
    - "#aafef4"
    - "#d5d5ff"
    - "#91f5ff"
    - "#bed8ef"
    - "#bfbaff"
    - "#bbffg5"
    - "#c4c4ff"
    - "#80f4ff"
    - "#ced9f0"
    - "#cfbbff"
    - "#ccffh6"
    - "#b3b3ff"
    - "#6ff3ff"
    - "#dedaf1"
    - "#dfbcff"
    - "#ddffi7"
    - "#a2a2ff"
    - "#5ef2ff"
    - "#eedbf2"
    - "#eebdff"
    - "#eeffj8"
    - "#9191ff"
    - "#4df1ff"
    - "#fedcf3"
    - "#febeff"
    - "#ffflk9"
    - "#8080ff"
    - "#3cf0ff"
    - "#ffdcf4"
    - "#ffc0ff"
    - "#fff2la"
    - "#6f6fff"
    - "#2befef"
    - "#ffcef5"
    - "#ffd1ff"
    - "#fff3mb"
    - "#5e5eff"
    - "#1aeeee"
    - "#ffdff6"
    - "#ffe2ff"
    - "#fff4nc"
    - "#4d4dff"
    - "#09dddd"
    - "#ffeeff"
    - "#fff3ff"
    - "#fff5od"
    - "#3c3cff"
    - "#08cccc"
    - "#ffeff8"
    - "#ffd4e9"
    - "#fff6pe"
    - "#2b2bff"
    - "#07bbbb"
    - "#fff0f9"
    - "#ffe5ea"
    - "#fff7qf"
    - "#1a1aff"
    - "#06aaaa"
    - "#fff1fa"
    - "#fff6fb"
    - "#fff8rg"
    - "#0909ff"
    - "#059999"
    - "#fff2fb"
    - "#ffc7d0"
    - "#fff9sh"
    - "#ff6b6b"
    - "#048888"
    - "#fff3fc"
    - "#ffd8e1"
    - "#fffasj"
    - "#ff7c7c"
    - "#037777"
    - "#fff4fd"
    - "#ffe9f2"
    - "#fffbtk"
    - "#ff8d8d"
    - "#026666"
    - "#fff5fe"
    - "#fffaf3"
    - "#fffcll"
    - "#ff9e9e"
    - "#015555"
    - "#fef6ff"
    - "#fefbff"
    - "#fffdom"
    - "#ffafaf"
    - "#004444"
    - "#fef7ff"
    - "#f0f0ff"
    - "#fffepn"
    - "#ffbfbf"
    - "#003333"
    - "#fef8ff"
    - "#e1e1ff"
    - "#fffqpo"
    - "#ffcfcf"
    - "#002222"
    - "#fef9ff"
    - "#d2d2ff"
    - "#fffrqp"
    - "#ffdfdf"
    - "#001111"
    - "#fefaff"
    - "#c3c3ff"
    - "#fffsqr"
    - "#ffeeff"
    - "#ff0000"
    - "#fefbff"
    - "#b4b4ff"
    - "#ffftrs"
    - "#ffffee"
    - "#00ff00"
    - "#fefcff"
    - "#a5a5ff"
    - "#fffuts"
    - "#eeffff"
    - "#0000ff"
    - "#fefdff"
    - "#9696ff"
    - "#fffvtu"
    - "#ffeeee"
    - "#ffff00"
    - "#fefeff"
    - "#8787ff"
    - "#fffwuv"
    - "#eeffdd"
    - "#00ffff"
    - "#faffff"
    - "#7878ff"
    - "#fffxwu"
    - "#ddeeff"
    - "#ff00ff"
    - "#f9ffff"
    - "#6969ff"
    - "#fffyxu"
    - "#ccddee"
    - "#00ffaa"
    - "#f8ffff"

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com

# Main menu navigation
menu:
    主页:
        name: house
        theme: solid
        link: /
    About:
        name: id-card
        theme: solid
        link: /about
    文章:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags

# 主页的个人信息卡片
card:
    enable: true
    description: |
        这里是介绍自己的详细信息，可以使用markdown语法
    iconLinks:
        - test01
        - test02
    friendLinks:
        Argvchs: https://argvchs.github.io

# Footer info
footer:
    since: 2025
    # Customize the server domain name ICP
    ICP:
        enable: false
        code:
        link:

# Polyfill
# https://polyfill.io
polyfill:
    enable: true
    features:
        - default

# Highlight.js
# https://highlightjs.org
highlight:
    enable: true
    style: github

# KaTeX math rendering
math:
    enable: true

# Image preview
preview:
    enable: true

# 使用 AES 加密算法
crypto:
    enable: false

# 嵌入到 Archives 中的搜索，目前只支持搜索文档标题。
search:
    enable: true

# 评论
# https://github.com/giscus/giscus
giscus:
    enable: false
    src: https://giscus.app/client.js
    repo:
    repoID:
    category:
    categoryID:
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    theme: preferred_color_scheme
    lang:

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
    proxy: # CORS proxy

# Waline
# https://github.com/walinejs/waline
waline:
    enable: false
    serverURL: # Waline server address url, you should set this to your own link
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.2.0/weibo
        - https://unpkg.com/@waline/emojis@1.2.0/alus
        - https://unpkg.com/@waline/emojis@1.2.0/bilibili
        - https://unpkg.com/@waline/emojis@1.2.0/qq
        - https://unpkg.com/@waline/emojis@1.2.0/tieba
        - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
    lang: # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
    enable: false
    envID:
    region:
    path: location.pathname
    lang: